
# Makefile to build the documentation

# Note, to convert LaTeX -> PDF, you might need a bunch of LaTeX packages. 
# On Ubuntu, run
#  sudo apt-get install texlive-latex-base \
#    texlive-extra-utils texlive-latex-recommended
#

plan:
	pdflatex ProjectPlan.tex
